export const defaultSettings = {
  general: {
    stone_config: {
      stone_types: [
        {
          id: "lab",
          label: "Lab Grown",
          enabled: true,
          feed_type: "CSV",
          feed_config: {},
          forward_order: false,
        },
        {
          id: "natural",
          label: "Natural",
          enabled: true,
          feed_type: "CSV",
          feed_config: {},
          forward_order: false,
        },
        {
          id: "gemstones",
          label: "Gemstones",
          enabled: true,
          feed_type: "CSV",
          feed_config: {},
          forward_order: false,
        },
      ],
      show_certificate: true,
    },
    theme_colors: {
      "theme-primary-color": "#0057A3",
      "theme-secondary-color": "#0057A326",
      "theme-primary-text-color": "#000000",
      "theme-secondary-text-color": "#515151",
      "theme-primary-color-hover": "#0068C2",
      "navigation-active-bg-color": "#C5E4FF26",
      "primary-color-disabled": "#8aaefd",
      "theme-button-color-primary": "#ffffff",
      "page-bg-color": "#ffffff",
    },
    feature_title: "<p>We’ve Got You Covered</p>",
    features: [
      {
        id: "feature-1",
        text: "Free Shipping & Returns",
        file: undefined,
        url: "/ring-builder/ring-builder-ui/assets/features/shipping.svg",
      },
      {
        id: "feature-2",
        text: "Free Lifetime Warranty",
        file: undefined,
        url: "/ring-builder/ring-builder-ui/assets/features/warranty.svg",
      },
      {
        id: "feature-3",
        text: "Lifetime Diamond Upgrade",
        file: undefined,
        url: "/ring-builder/ring-builder-ui/assets/features/diamond.svg",
      },
      {
        id: "feature-4",
        text: "Free 1-Year Resizing",
        file: undefined,
        url: "/ring-builder/ring-builder-ui/assets/features/resize-ring.svg",
      },
    ],
  },
  diamond: {
    shapes: [
      {
        id: "1",
        key: "round",
        label: "Round",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/round.svg",
      },
      {
        id: "2",
        key: "oval",
        label: "Oval",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/oval.svg",
      },
      {
        id: "3",
        key: "emerald",
        label: "Emerald",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/emerald.svg",
      },
      {
        id: "4",
        key: "cushion",
        label: "Cushion",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/cushion.svg",
      },
      {
        id: "5",
        key: "pear",
        label: "Pear",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/pear.svg",
      },
      {
        id: "6",
        key: "radiant",
        label: "Radiant",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/radiant.svg",
      },
      {
        id: "7",
        key: "heart",
        label: "Heart",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/heart.svg",
      },
      {
        id: "8",
        key: "princess",
        label: "Princess",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/princess.svg",
      },
      {
        id: "9",
        key: "marquise",
        label: "Marquise",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/marquise.svg",
      },
      {
        id: "10",
        key: "asscher",
        label: "Asscher",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/asscher.svg",
      },
    ],
    filters: {
      lab: [
        {
          id: "carat",
          label: "Carat",
          values: { min: 1, max: 10 },
          enabled: true,
        },
        {
          id: "colors",
          label: "Colors",
          values: ["D", "E", "F", "G", "H", "I", "J"],
          enabled: true,
        },
        {
          id: "clarity",
          label: "Clarity",
          values: ["FL", "IF", "VVS1", "VVS2", "VS1", "VS2", "SI1", "SI2"],
          enabled: true,
        },
        {
          id: "price",
          label: "Price",
          values: { min: 100, max: 5000 },
          enabled: true,
        },
        {
          id: "cut",
          label: "Cut",
          values: ["ID", "EX", "VG", "GD", "F"],
          enabled: false,
        },
        {
          id: "report",
          label: "Report",
          values: ["GIA", "IGI", "HRD", "GCAL", "SGL"],
          enabled: false,
        },
        {
          id: "polish",
          label: "Polish",
          values: ["ID", "EX", "VG"],
          enabled: false,
        },
        {
          id: "fluorescence",
          label: "Fluorescence",
          values: ["none", "faint", "medium", "strong", "very_strong"],
          enabled: false,
        },
      ],
      natural: [
        {
          id: "carat",
          label: "Carat",
          not_changeable: true,
          values: { min: 1, max: 10 },
          enabled: true,
        },
        {
          id: "colors",
          label: "Colors",
          not_changeable: true,
          values: ["D", "E", "F", "G", "H", "I", "J"],
          enabled: true,
        },
        {
          id: "clarity",
          label: "Clarity",
          not_changeable: true,
          values: ["FL", "IF", "VVS1", "VVS2", "VS1", "VS2", "SI1", "SI2"],
          enabled: true,
        },
        {
          id: "price",
          label: "Price",
          not_changeable: true,
          values: { min: 100, max: 5000 },
          enabled: true,
        },
        {
          id: "cut",
          label: "Cut",
          values: ["ID", "EX", "VG", "GD", "F"],
          enabled: false,
        },
        {
          id: "report",
          label: "Report",
          values: ["GIA", "IGI", "HRD", "GCAL", "SGL"],
          enabled: false,
        },
        {
          id: "polish",
          label: "Polish",
          values: ["ID", "EX", "VG"],
          enabled: false,
        },
        {
          id: "fluorescence",
          label: "Fluorescence",
          values: ["none", "faint", "medium", "strong", "very_strong"],
          enabled: false,
        },
      ],
    },
  },
  ring: {
    metals: [
      {
        id: "1",
        key: "platinum",
        label: "Platinum",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/metals/metal_platinum.png",
      },
      {
        id: "2",
        key: "yellow_gold",
        label: "Yellow Gold",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/metals/metal_yellow_gold.png",
      },
      {
        id: "3",
        key: "white_gold",
        label: "White Gold",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/metals/metal_white_gold.png",
      },
      {
        id: "4",
        key: "rose_gold",
        label: "Rose Gold",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/metals/metal_rose_gold.png",
      },
    ],
    styles: [
      {
        id: "1",
        url: "/ring-builder/ring-builder-ui/assets/ring-settings/Solitaire.svg",
        label: "Solitaire",
        enabled: true,
        key: "Solitaire",
      },
      {
        id: "2",
        url: "/ring-builder/ring-builder-ui/assets/ring-settings/Pave.svg",
        label: "Pave",
        enabled: true,
        key: "Pave",
      },
      {
        id: "3",
        url: "/ring-builder/ring-builder-ui/assets/ring-settings/Halo.svg",
        label: "Halo",
        enabled: true,
        key: "Halo",
      },
      {
        id: "4",
        url: "/ring-builder/ring-builder-ui/assets/ring-settings/NatureInspired.svg",
        label: "Nature Inspired",
        enabled: true,
        key: "Nature Inspired",
      },
      {
        id: "5",
        url: "/ring-builder/ring-builder-ui/assets/ring-settings/HiddenHalo.svg",
        label: "Hidden Halo",
        enabled: true,
        key: "Hidden halo",
      },
      {
        id: "6",
        url: "/ring-builder/ring-builder-ui/assets/ring-settings/Accents.svg", // "side_stones" matches "Accents"
        label: "Side Stones",
        enabled: true,
        key: "Side Stones",
      },
      {
        id: "7",
        url: "/ring-builder/ring-builder-ui/assets/ring-settings/Vintage.svg",
        label: "Vintage",
        enabled: true,
        key: "Vintage",
      },
      {
        id: "8",
        url: "/ring-builder/ring-builder-ui/assets/ring-settings/Bezel.svg",
        label: "Bezel",
        enabled: true,
        key: "Bezel",
      },
      {
        id: "9",
        url: "/ring-builder/ring-builder-ui/assets/ring-settings/Cathedral.svg",
        label: "Cathedral",
        enabled: true,
        key: "Cathedral",
      },
      {
        id: "10",
        url: "/ring-builder/ring-builder-ui/assets/ring-settings/East-West.svg",
        label: "East West",
        enabled: true,
        key: "East West",
      },
      {
        id: "11",
        url: "/ring-builder/ring-builder-ui/assets/ring-settings/ThreeStone.svg",
        label: "Three Stone",
        enabled: true,
        key: "3 Stone",
      },
    ],
    filters: [
      {
        id: "price",
        label: "Price",
        enabled: true,
        values: { min: 500, max: 3000 },
      },
    ],
    result_style: "paginated",
    page_title: "Engagement Rings",
    show_add_to_cart: false,
    page_subtitle:
      "Oval engagement rings are exquisitely cut into an elongated shape that lengthens the finger.",
    default_pagination: "pagination-4",
  },
  gemstone: {
    shapes: [
      {
        id: "1",
        key: "round",
        label: "Round",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/round.svg",
      },
      {
        id: "2",
        key: "oval",
        label: "Oval",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/oval.svg",
      },
      {
        id: "3",
        key: "emerald",
        label: "Emerald",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/emerald.svg",
      },
      {
        id: "4",
        key: "cushion",
        label: "Cushion",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/cushion.svg",
      },
      {
        id: "5",
        key: "pear",
        label: "Pear",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/pear.svg",
      },
      {
        id: "6",
        key: "radiant",
        label: "Radiant",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/radiant.svg",
      },
      {
        id: "7",
        key: "princess",
        label: "Princess",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/princess.svg",
      },
      {
        id: "8",
        key: "marquise",
        label: "Marquise",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/marquise.svg",
      },
      {
        id: "9",
        key: "asscher",
        label: "Asscher",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/asscher.svg",
      },
      {
        id: "10",
        key: "heart",
        label: "Heart",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/shapes/heart.svg",
      },
    ],
    types: [
      {
        id: "1",
        key: "sapphire",
        label: "Sapphire",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Sapphire.webp",
      },
      {
        id: "2",
        key: "moissanite",
        label: "Moissanite",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Moissanite.webp",
      },
      {
        id: "3",
        key: "emerald",
        label: "Emerald",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Emerald.webp",
      },
      {
        id: "4",
        key: "colored_diamond",
        label: "Colored Diamond",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Diamond.webp",
      },
      {
        id: "5",
        key: "aquamarine",
        label: "Aquamarine",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Aquamarine.webp",
      },
      {
        id: "6",
        key: "alexandrite",
        label: "Alexandrite",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Alexandrite.webp",
      },
      {
        id: "7",
        key: "morganite",
        label: "Morganite",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Morganite.webp",
      },
      {
        id: "8",
        key: "pacific_green",
        label: "pacific green",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/pacific_green.webp",
      },
      {
        id: "9",
        key: "garnet",
        label: "Garnet",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Garnet.webp",
      },
      {
        id: "10",
        key: "ruby",
        label: "Ruby",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Ruby.webp",
      },
      {
        id: "11",
        key: "topaz",
        label: "Topaz",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Topaz.webp",
      },
      {
        id: "12",
        key: "tanzanite",
        label: "Tanzanite",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Tanzanite.webp",
      },
      {
        id: "13",
        key: "tourmaline",
        label: "Tourmaline",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Tourmaline.webp",
      },
      {
        id: "14",
        key: "amethyst",
        label: "Amethyst",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Amethyst.webp",
      },
      {
        id: "15",
        key: "sunstone",
        label: "Sunstone",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Sunstone.webp",
      },
      {
        id: "16",
        key: "spinel",
        label: "Spinel",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Spinel.webp",
      },
      {
        id: "17",
        key: "peridot",
        label: "Peridot",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Peridot.webp",
      },
      {
        id: "18",
        key: "citrine",
        label: "Citrine",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Citrine.webp",
      },
      {
        id: "19",
        key: "other",
        label: "Other",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Other.webp",
      },
      {
        id: "20",
        key: "antique_diamond",
        label: "Antique Diamond",
        enabled: true,
        url: "/ring-builder/ring-builder-ui/assets/gemstone/Vintage_Diamond.webp",
      },
    ],
    filters: [
      {
        id: "carat",
        label: "Carat",
        values: { min: 1, max: 10 },
        enabled: true,
      },
      {
        id: "colors",
        label: "Colors",
        values: [
          "blue",
          "green",
          "pink",
          "white",
          "teal",
          "purple",
          "yellow",
          "red",
          "orange",
        ],
        enabled: true,
      },
      {
        id: "price",
        label: "Price",
        values: { min: 500, max: 100000 },
        enabled: true,
      },
      {
        id: "clarity",
        label: "Clarity",
        status: "secondary",
        values: ["si2", "si1", "vs2", "vs1", "vvs2", "vvs1", "if", "fl"],
        enabled: false,
      },
      {
        id: "cut",
        label: "Cut",
        status: "secondary",
        values: ["F", "GD", "VG", "Ex", "ID"],
        enabled: false,
      },
      {
        id: "report",
        label: "Report",
        status: "secondary",
        values: ["igi", "gia", "hrd", "sgl", "gcal"],
        enabled: false,
      },
    ],
  },
  complete_ring: {
    show_ring_size: true,
    size_values: "3,4,5,6,7,8,9,10",
    show_engravings: false,
  },
  stone_appearance: {
    listing_page: {
      page_title: "<p>Design Your Own Engagement Ring</p>",
      default_sort: "price_asc",
      default_view: "grid",
      result_style: "paginated",
      page_subtitle:
        "<p>Forever has a nice ring to it. It all starts by selecting a setting and your dream diamond to create your made-to-order design engagement ring.</p>",
      selected_view: [
        { id: "grid", label: "Grid", enabled: true },
        { id: "list", label: "List", enabled: true },
      ],
      sorting_options: [
        { id: "price", label: "Price", enabled: true },
        { id: "carat", label: "Carat", enabled: true },
      ],
      default_pagination: "pagination-4",
    },
    view_page: {
      stone_title: "<p>{carat} Carat {shape} Shape Diamond</p>",
      show_add_to_cart: false,
      featured_images: {
        lab: [],
        natural: [],
        gemstones: [],
      },
      show_certificate: true,
      selected_details: [
        { id: "type", label: "Origin", enabled: true },
        { id: "selling_price", label: "Price", enabled: true },
        { id: "carat", label: "Carat Weight", enabled: true },
        { id: "shape", label: "Shape", enabled: true },
        { id: "cut", label: "Cut", enabled: true },
        { id: "color", label: "Color", enabled: true },
        { id: "clarity", label: "Clarity", enabled: true },
        { id: "measurements", label: "Measurements", enabled: true },
        { id: "table", label: "Table", enabled: true },
        { id: "depth", label: "Depth", enabled: true },
        { id: "symmetry", label: "Symmetry", enabled: true },
        { id: "polish", label: "Polish", enabled: true },
        { id: "girdle", label: "Girdle", enabled: true },
        { id: "culet", label: "Culet", enabled: true },
        { id: "fluorescence", label: "Fluorescence", enabled: true },
        { id: "lwRatio", label: "Length-To-Width Ratio", enabled: true },
      ],
    },
  },
};
